Vagrant.configure("2") do |config|
    servers=[
      {
        :hostname => "akil-project",
        :box => "bento/ubuntu-18.04",
        :ssh_port => '2225'
      }
    ]
    
    servers.each do |machine|
  
      config.vm.define machine[:hostname] do |node|
        node.vm.box = machine[:box]
        node.vm.hostname = machine[:hostname]
  
        node.vm.network :public_network, ip: "192.168.1.190"
        # node.vm.network :private_network, type: "dhcp"
        node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
  
        node.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--memory", 3072]
          v.customize ["modifyvm", :id, "--name", machine[:hostname]]
        end
        node.vm.provision "shell", path: "script.sh"
      end
    end
  end